apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "test"
    effect: "NoSchedule"
 



##  kubectl taint nodes node1 key1=value1:NoSchedule
##  kubectl taint nodes node1 key1=value1:NoExecute
##  kubectl taint nodes node1 key2=value2:NoSchedule