apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate
  labels:
    app: siebel
spec:
  replicas: 10
  selector:
    matchLabels:
      app: siebel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: siebel
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80