apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color
  labels:
        app: simple-webapp
spec:
  containers:
    - name: simple-webapp-color
      image: enespekdas/simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config