apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-lbsvc
spec:
  type: LoadBalancer
  selector:
    app: simple-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080